name: Deploy to VDS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Copy files via SSH
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VDS_HOST }}
                  username: ${{ secrets.VDS_USER }}
                  key: ${{ secrets.VDS_SSH_KEY }}
                  port: 22
                  source: "."
                  target: "/srv/ahtyler/portfolio"

            - name: Run deploy script via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VDS_HOST }}
                  username: ${{ secrets.VDS_USER }}
                  key: ${{ secrets.VDS_SSH_KEY }}
                  port: 22
                  script: |
                      cd /srv/ahtyler/portfolio
                      sudo pnpm install
                      sudo pnpm run build
                      sudo pm2 restart ahtyler-portfolio
